class Cursor{constructor(){this.cursor=document.querySelector('.cursor');this.triggers=document.querySelectorAll('[data-cursor-type]');this._attachEvents();}
_attachEvents(){this.triggers.forEach(trigger=>{trigger.addEventListener('mouseenter',this._mouseEnterHandler.bind(this));trigger.addEventListener('mousemove',this._mouseMoveHandler.bind(this));trigger.addEventListener('mouseleave',this._mouseLeaveHandler.bind(this));});}
_showCursor(type){this.cursor.style.display='block';document.documentElement.classList.add('hide-cursor');if(type)this.cursor.classList.add(type);}
_hideCursor(type){this.cursor.style.display='none';document.documentElement.classList.remove('hide-cursor');if(type)this.cursor.classList.remove(type);}
_mouseMoveHandler(e){if(e.target?.closest('[data-no-cursor]'))this._hideCursor();else this._showCursor();this.cursor.style.transform=`translate3d(${e.clientX}px,${e.clientY}px, 0)`;}
_mouseEnterHandler(e){this._mouseMoveHandler(e);this._showCursor(e.currentTarget.dataset.cursorType);}
_mouseLeaveHandler(e){this._hideCursor(e.currentTarget.dataset.cursorType);}}
window.Cursor=Cursor;;;class InterestsNav{NAV_OPEN_CLASS='interests-nav-open';constructor(){this.nav=document.querySelector('[data-interests-nav]');this.triggers=document.querySelectorAll('[data-toggle-interests-nav]');this.isOpen=false;this._attachEvents();}
get isOpen(){return this._isOpen??false;}
set isOpen(isOpen){this._isOpen=isOpen;document.documentElement.classList.toggle(this.NAV_OPEN_CLASS,isOpen);}
_attachEvents(){this.nav?.addEventListener('click',this._handleNavClick.bind(this));this.triggers.forEach(trigger=>{trigger.addEventListener('click',()=>{this.isOpen=!this.isOpen;});});}
_handleNavClick(e){const toggle=e.target.closest('[data-toggle-interests-nav]');if(toggle)return;const link=e.target.closest('a');if(!link){this.isOpen=false;return;}
e.preventDefault();this.isOpen=false;document.documentElement.classList.remove('bg-animation');gsap.to(document.querySelector('[data-grid]'),{opacity:0,scale:0,duration:0.5,overwrite:true,}).then(()=>{location=link.href;});}}
window.InterestsNav=InterestsNav;;;class RandomizeOrder{constructor(el){this.el=el;this.init();}
init(){for(let i=this.el.children.length;i>=0;i--){const randomEl=this.el.children[(Math.random()*i)|0];this.el.appendChild(randomEl);}}}
window.RandomizeOrder=RandomizeOrder;;;class MacroHomeGrid{DRAG_TRESHOLD=10;MAX_DRIFT=3;DRIFT_X_MULTIPLIER=1;DRIFT_Y_MULTIPLIER=1;constructor(macro){this.macro=macro;this.grid=this.macro.querySelector('[data-grid]');this.gridItems=Array.from(this.grid.children);this.lastDownX=0;this.lastDownY=0;this.dragDeltaX=0;this.dragDeltaY=0;this.velocityX=0;this.velocityY=0;this.velocityMultiplier=2;this.isMobile=matchMedia('(max-width: 767px)').matches;this._attachEvents();}
_getCurrentBreakpoint(){if(matchMedia('(min-width: 1024px)').matches)return'large';if(matchMedia('(min-width: 768px)').matches)return'medium';return'small';}
_attachEvents(){window.addEventListener('load',()=>{this.scrollBoosterInstance=this._initScrollBooster();gsap.set(this.gridItems,{opacity:0});gsap.to(this.gridItems,{opacity:1,duration:'random(0.25, 1.5)',delay:'random(0, 1.2)',});const isSafari=navigator.userAgent.includes('Safari')&&!navigator.userAgent.includes('Chrome');gsap.set(this.grid,{opacity:0,scale:isSafari?1:0});gsap.to(this.grid,{opacity:1,scale:1,duration:2,ease:'power1.inOut',}).then(()=>{this._initParallax();this._animationLoop();});});window.addEventListener('pageshow',e=>{if(e.persisted)location.reload();});document.addEventListener('mousemove',this._mouseMoveHandler.bind(this));document.addEventListener('mouseleave',()=>{this.velocityX=0;this.velocityY=0;});this.macro.addEventListener('pointerdown',this._pointerDownHandler.bind(this));this.macro.addEventListener('pointerup',this._pointerUpHandler.bind(this));this.gridItems.forEach(gridItem=>{gridItem.addEventListener('pointerenter',this._pointerEnterHandler.bind(this),{once:true,});gridItem.addEventListener('click',this._clickHandler.bind(this));});}
_mouseMoveHandler(e){const normalizedX=(e.pageX/window.innerWidth)*2-1;const normalizedY=(e.pageY/window.innerHeight)*2-1;let easedX=Power1.easeInOut(normalizedX)*this.velocityMultiplier;let easedY=Power1.easeInOut(normalizedY)*this.velocityMultiplier;if(easedX<0.1)easedX=0;if(easedY<0.1)easedY=0;this.velocityX=Math.sign(normalizedX)===-1?-easedX:easedX;this.velocityY=Math.sign(normalizedY)===-1?-easedY:easedY;}
_pointerDownHandler(e){this.lastDownX=e.pageX;this.lastDownY=e.pageY;}
_pointerUpHandler(e){this.dragDeltaX=Math.abs(this.lastDownX-e.pageX);this.dragDeltaY=Math.abs(this.lastDownY-e.pageY);}
_pointerEnterHandler(e){const fullImg=e.currentTarget.querySelector('[data-src-large]');const img=new Image();const newSrc=fullImg.getAttribute(`data-src-${this._getCurrentBreakpoint()}`);img.src=newSrc;}
_clickHandler(e){if(this.dragDeltaX>this.DRAG_TRESHOLD||this.dragDeltaY>this.DRAG_TRESHOLD){return;}
if(this.isMobile)return;const clickedEl=e.currentTarget;const href=clickedEl.getAttribute('href');if(!href)return;const fullImg=clickedEl.querySelector('[data-src-large]');document.documentElement.classList.add('lock-interactions');fullImg.src=fullImg.getAttribute(`data-src-${this._getCurrentBreakpoint()}`);const state=Flip.getState(fullImg);document.body.appendChild(fullImg);e.preventDefault();gsap.to(this.gridItems,{opacity:0,duration:0.6,});Flip.from(state,{duration:1.5,ease:'power3.inOut',onComplete:()=>{location=href;},});}
_onUpdate(state){const contentRect=this.grid.getBoundingClientRect();const posX=state.position.x/(contentRect.width-this.macro.offsetWidth);const posY=state.position.y/(contentRect.height-this.macro.offsetHeight);document.documentElement.classList.toggle('home-fade-text',state.position.y>50);this.gridItems.forEach(item=>{const{driftX,driftY,directionX,directionY}=item.dataset;if(this.isMobile||[driftX,driftY].every(num=>num==='0'))return;const x=(posX*2-1)*Number(driftX)*Number(directionX)*this.DRIFT_X_MULTIPLIER*this.MAX_DRIFT;const y=(posY*2-1)*Number(driftY)*Number(directionY)*this.DRIFT_Y_MULTIPLIER*this.MAX_DRIFT;item.style.transform=`translate3d(${x}rem,${y}rem,0)`;});this.grid.style.transformOrigin=`calc(${state.position.x}px + 50vw) calc(${state.position.y}px + 50vh)`;}
_animationLoop(){if(this.scrollBoosterInstance){const state=this.scrollBoosterInstance.getState();this.scrollBoosterInstance.setPosition({x:state.position.x+this.velocityX,y:state.position.y+this.velocityY,});}
requestAnimationFrame(this._animationLoop.bind(this));}
_initScrollBooster(){const sbInstance=new ScrollBooster({viewport:this.macro,content:this.grid,scrollMode:'native',friction:0.1,bounce:false,onUpdate:this._onUpdate.bind(this),});const offsetX=this.grid.scrollWidth-this.macro.offsetWidth;sbInstance.setPosition({x:offsetX/2,y:0});return sbInstance;}
_initParallax(){this.gridItems.forEach((item,i)=>{const isMedium=(i+1)%3===0;const isLarge=(i+2)%3===0;item.setAttribute('data-drift-x',String(Number(isLarge)||Number(isMedium)/2));item.setAttribute('data-drift-y',String(Number(isLarge)||Number(isMedium)/2));item.setAttribute('data-direction-x','-1');item.setAttribute('data-direction-y','-1');});}}
window.MacroHomeGrid=MacroHomeGrid;;;